# Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
def handle(a,b):
    try:
        c = a/b
        print(c)
    except:
        print("Error: Arithmetic Error occured")
    else:
        print("There is no Exception occured")
    finally:
        print("I am always executed")

In [7]:
handle(5,0)

Error: Arithmetic Error occured
I am always executed


In [8]:
handle(10,2)

5.0
There is no Exception occured
I am always executed


# Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [9]:
subjects = ["Americans", "Indians"]
verbs = ["play","watch"]
objects = ["Baseball","cricket"]

for x in subjects:
    for y in verbs:
        for z in objects:
            print(x+" "+y+" "+z+".")

Americans play Baseball.
Americans play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians play Baseball.
Indians play cricket.
Indians watch Baseball.
Indians watch cricket.


# Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [14]:
import numpy as np
list = [1,2,3,4]
n = 4
array = np.array([[list[i]**(n-(j+1)) for j in range (0,n)] for i in range(len(list))])

In [15]:
print(array)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [13]:
for i in range(len(list)):
    print(i)

0
1
2
3
